### ISSUE TITLE
Configure file extensions for Coffee JSX and regular JSX separately.

### ISSUE THREAD

**Issue by iamdanfox** [reactjs/sublime-react#15]
At the moment the `JSX.sublime-settings` file allows you to specify a list of `extensions`, but it doesn't differentiate between Coffee and Javascript syntax!

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting, and has been superseded by the babel/babel-sublime package.
Since Babel unfortunately does not support CoffeeScript, I recommend that someone set up a new repo+package to maintain CoffeeScript separately (it could be you! :)
Thank you for your understanding.
