### ISSUE TITLE
May not work in latest Sublime?

### ISSUE THREAD

**Issue by alanhogan** [reactjs/sublime-react#17]
I just updated Sublime Text to build 3065 and got this error:

![screen shot 2014-08-29 at 2 31 56 pm](https://cloud.githubusercontent.com/assets/6808/4096718/6ec891de-2fc5-11e4-96f4-9d507255a8d7.png)

Also updated was the “Better CoffeeScript” package, so maybe there is some sort of conflict there?

**Comment by jenskanis** [comment]
@alanhogan your having the same issues as us? #42

**Comment by alanhogan** [comment]
Seemed different @jenskanis but I have not tried Sublime in months

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting, and has been superseded by the babel/babel-sublime package.
Since Babel unfortunately does not support CoffeeScript, I recommend that someone set up a new repo+package to maintain CoffeeScript separately (it could be you! :)
Thank you for your understanding.
