### ISSUE TITLE
Syntax highlighting bug when wrapping lines

### ISSUE THREAD

**Issue by QuotableWater7** [reactjs/sublime-react#35]
The following syntax messes up the parsing:
```
<input
  className='blah'
  something=5
/>
```
Real world example:
![screen shot 2015-01-26 at 11 16 19 am](https://cloud.githubusercontent.com/assets/2163763/5906478/cf8a88ea-a54c-11e4-9a07-127e14fb82e6.png)

**Comment by treyp** [comment]
I had this problem, too, but it turns out I just overlooked some of the instructions in [the usage section of the README](https://github.com/reactjs/sublime-react#syntax-highlighting).

You need to switch to the ReactJS syntax highlighting after installation. You can default to that by opening a JSX file and then, in the bottom right, change `JavaScript` to `Open all with current extension as...` > `ReactJS` > `JavaScript (JSX)`.

**Comment by QuotableWater7** [comment]
Oh, beautiful...  Thanks man
