### ISSUE TITLE
Comments are rendered weird when using CoffeeScript

### ISSUE THREAD

**Issue by binarykitchen** [reactjs/sublime-react#40]
Somehow this plugin does not render the CoffeeScript comments properly. Those preceeding `#` ...

Not sure if it's a bug or something else.

**Comment by noinkling** [comment]
They render fine for me up until a certain a point, then the syntax highlighting becomes pretty broken in general (includes comments). See the update portion of the issue I opened at #39.

**Comment by binarykitchen** [comment]
Thanks @noinkling ... this bug really makes it harder for us to write React with CoffeeScript. Any chance this can be fixed real soon?

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting, and has been superseded by the babel/babel-sublime package.
Since Babel unfortunately does not support CoffeeScript, I recommend that someone set up a new repo+package to maintain CoffeeScript separately (it could be you! :)
Thank you for your understanding.

**Comment by binarykitchen** [comment]
i understand
