### ISSUE TITLE
Please re-enable syntax highlighting for coffeescript.

### ISSUE THREAD

**Issue by DylanPiercey** [reactjs/sublime-react#45]
This is currently the only package that supports CJSX (babel does not). As such it would be great if the syntax highlighting remained.

**Comment by jgebhardt** [comment]
This package no longer provides syntax highlighting, and has been superseded by the babel/babel-sublime package.
Since Babel unfortunately does not support CoffeeScript, I recommend that someone set up a new repo+package to maintain CoffeeScript separately (it could be you! :)
Thank you for your understanding.
